<?php

/**
 * @file
 * Contains tt_defaults.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tt_defaults_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the tt_defaults module.
        case 'help.page.tt_defaults':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('TT standards for Drupal 8') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_preprocess_html().
 */
function tt_defaults_preprocess_html(&$variables)
{
    $disabledHTMLHead = ['system_meta_generator', 'HandheldFriendly', 'MobileOptimized'];

    // Remove HTML head attributes
    foreach ($variables['page']['#attached']['html_head'] as $index => $html_head) {
        if (in_array($html_head[1], $disabledHTMLHead)) {
            unset($variables['page']['#attached']['html_head'][$index]);
        }
    }

    // Don't display the site name twice on the front page (and potentially others)
    if (isset($variables['head_title_array']['title']) && isset($variables['head_title_array']['name']) && ($variables['head_title_array']['title'] == $variables['head_title_array']['name'])) {
        $variables['head_title'] = $variables['head_title_array']['name'];
    }

    unset($variables['html_attributes']['xmlns:dc']);
    unset($variables['html_attributes']['xmlns:og']);
    unset($variables['html_attributes']['xmlns:article']);
    unset($variables['html_attributes']['xmlns:book']);
    unset($variables['html_attributes']['xmlns:profile']);
    unset($variables['html_attributes']['xmlns:video']);
    unset($variables['html_attributes']['xmlns:product']);
}

/**
 * Implements hook_page_attachments_alter().
 */
function tt_defaults_page_attachments_alter(array &$page)
{
    // Tell IE to use latest rendering engine (not to use compatibility mode).
    /*$ie_edge = [
      '#type' => 'html_tag',
      '#tag' => 'meta',
      '#attributes' => [
      'http-equiv' => 'X-UA-Compatible',
      'content' => 'IE=edge',
      ],
    ];
    $page['#attached']['html_head'][] = [$ie_edge, 'ie_edge'];*/

    unset($page['#attached']['html_head_link']);
}

function tt_defaults_js_alter(&$javascript, \Drupal\Core\Asset\AttachedAssetsInterface $assets)
{
    if (\Drupal::currentUser()->isAuthenticated()) {
        return true;
    }

    $remove = [
        'core/assets/vendor/modernizr/modernizr.min.js',
        'core/assets/vendor/html5shiv/html5shiv.min.js',
        'modules/contrib/improved_multi_select/improved_multi_select.js',
    ];

    foreach ($javascript as $js => $values) {
        if (!in_array($js, $remove)) {
            continue;
        }

        unset($javascript[$js]);
    }
}

function tt_defaults_css_alter(&$css, \Drupal\Core\Asset\AttachedAssetsInterface $assets)
{
    if (\Drupal::currentUser()->isAuthenticated()) {
        return true;
    }

    $remove = [
        'core/themes/stable/css/system/components/ajax-progress.module.css',
        'core/themes/stable/css/system/components/align.module.css',
        'core/themes/stable/css/system/components/autocomplete-loading.module.css',
        'core/themes/stable/css/system/components/fieldgroup.module.css',
        'core/themes/stable/css/system/components/container-inline.module.css',
        'core/themes/stable/css/system/components/clearfix.module.css',
        'core/themes/stable/css/system/components/details.module.css',
        'core/themes/stable/css/system/components/hidden.module.css',
        'core/themes/stable/css/system/components/item-list.module.css',
        'core/themes/stable/css/system/components/js.module.css',
        'core/themes/stable/css/system/components/nowrap.module.css',
        'core/themes/stable/css/system/components/position-container.module.css',
        'core/themes/stable/css/system/components/progress.module.css',
        'core/themes/stable/css/system/components/reset-appearance.module.css',
        'core/themes/stable/css/system/components/resize.module.css',
        'core/themes/stable/css/system/components/sticky-header.module.css',
        'core/themes/stable/css/system/components/tabledrag.module.css',
        'core/themes/stable/css/system/components/tablesort.module.css',
        'core/themes/stable/css/system/components/tree-child.module.css',
        'modules/contrib/improved_multi_select/improved_multi_select.css',
    ];

    foreach ($css as $id => $values) {
        if (!in_array($id, $remove)) {
            continue;
        }

        unset($css[$id]);
    }
}

function tt_defaults_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
    global $base_url;

    $is_front = \Drupal::service('path.matcher')->isFrontPage();

    if (!empty($build['#attached']['html_head_link'])) {

        foreach ($build['#attached']['html_head_link'] as $key => $config) {

            if ($config[0]['rel'] !== 'canonical') {
                unset($build['#attached']['html_head_link'][$key]);
            } elseif( $is_front === false ) {
                $build['#attached']['html_head_link'][$key][0]['href'] = $base_url . $build['#attached']['html_head_link'][$key][0]['href'];
            } else {
                $build['#attached']['html_head_link'][$key][0]['href'] = $base_url;
            }
        }
    }
}